@startuml

start

:User initiates sign out from LuvMatchApp;

:LuvMatchApp requests sign out from FirebaseAuth;

:FirebaseAuth confirms sign out is successful;

:LuvMatchApp informs User that sign out was successful;

stop

@enduml
