@startuml ForgotPassword
actor User
participant LuvMatchApp
participant FirebaseAuth

User -> LuvMatchApp: Initiates password reset
activate LuvMatchApp

LuvMatchApp -> FirebaseAuth: Request password reset email
activate FirebaseAuth

FirebaseAuth --> LuvMatchApp: Password reset email sent
deactivate FirebaseAuth

LuvMatchApp --> User: Password reset email sent successfully
deactivate LuvMatchApp

User -> LuvMatchApp: Follows the link in the email
activate LuvMatchApp

LuvMatchApp -> FirebaseAuth: Verify email link
activate FirebaseAuth

FirebaseAuth --> LuvMatchApp: Email link verified
deactivate FirebaseAuth

LuvMatchApp -> LuvMatchApp: Prompt user to reset password
LuvMatchApp --> User: User resets password
deactivate LuvMatchApp

@enduml