@startuml SignOut
actor User
participant LuvMatchApp
participant FirebaseAuth

User -> LuvMatchApp: Initiates sign out
activate LuvMatchApp

LuvMatchApp -> FirebaseAuth: Request sign out
activate FirebaseAuth

FirebaseAuth --> LuvMatchApp: Sign out successful
deactivate FirebaseAuth

LuvMatchApp -> User: Sign out successful
deactivate LuvMatchApp

@enduml