@startuml
start

:User provides old and new password;
:LuvMatchApp requests password change from FirebaseAuth;

if (Password change successful) then (yes)
    :LuvMatchApp informs User that password change was successful;
else (no)
    :LuvMatchApp informs User that password change failed;
endif

stop
@enduml
