@startuml
start

:User provides old and new password (1);
:LuvMatchApp requests password change from FirebaseAuth (2);

if (Password change successful (3)) then (yes)
    :LuvMatchApp informs User that password change was successful (4);
else (no)
    :LuvMatchApp informs User that password change failed (5);
endif

stop
@enduml
