@startuml

start

:Reporter reports a message from Sender on LuvMatchApp;

:LuvMatchApp stores the message report in ReportDatabase;

:ReportDatabase confirms message report is stored;

:LuvMatchApp informs Reporter that the report was submitted;

stop

@enduml
