@startuml
start
:Admin: as Admin
:Moderator: as Moderator
:User: as User

if (Admin or Moderator or User) then (yes)
 :Requests to view user profile:
 :Retrieve user profile:
 :User profile retrieved:
 :User profile displayed:
endif
stop
@enduml
