@startuml

start

:User enters username/password/confirm password on LoginGUI;

:User taps Sign up button on LoginGUI;

:LoginGUI sends sign up request to AuthenController;

:AuthenController validates the request with AuthenService;

if (User not already exist) then (yes)
   :AuthenController informs LoginGUI that registration was successful;
   :LoginGUI redirects User to MainScreenGUI;
else (no)
   :AuthenController informs LoginGUI that registration failed;
   :LoginGUI informs User that registration failed;
endif

stop

@enduml
