@startuml

start

:Admin requests to delete user account (1);

:LuvMatchApp retrieves user data from Database (2);

:LuvMatchApp deletes user account from Database (3);

:LuvMatchApp informs Admin that user account is deleted (4);

stop

@enduml
